<?php

/*
 * Implements hook_form_FORM_ID_alter()
*/
function json_data_form_system_site_information_settings_alter(&$form, $form_state, $form_id) {
  // Change form submit text to 'Update Configuration'
  $form['actions']['submit']['#value'] = t('Update configuration');

  // Handle form submission
  $form['#submit'][] = 'site_config_handler';
}

function site_config_handler($form, &$form_state) {
  // Add message that Site API Key has been set
  drupal_set_message("Site API Key saved with " . $form_state->getValue('siteapikey'));
}
